version: '3.0'

services:
  react-app:
    build:
      # 現在のディレクトリをビルドコンテキストとして使用
      context: .
      # Dockerfileもこのディレクトリにあることを前提
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      # ホストマシンの現在のディレクトリ（Reactアプリケーションのプロジェクトディレクトリ）をコンテナ内の/appディレクトリにマウント
      - .:/app
      - react-node-modules:/app/node_modules
    env_file:
      - .env.dev
    environment:
      # - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # Reactアプリケーションがファイルシステムの変更を監視する際に、ポーリングモードを有効
    networks:
      - my-network

networks:
  my-network:
volumes:
  react-node-modules: